# name: My Git-Profile
# title: "Hello Fellas"
# email: ryanpagaduan23@gmail.com
# baseurl: ""
# url: ""
# twitter_username: 
# github_username: RyaiStudio
# theme: jekyll-theme-cayman

sass: 
  sass_dir: _sass